# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_openinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactblock',
            options={'default_permissions': (), 'verbose_name': 'Contact block', 'verbose_name_plural': 'Contact blocks'},
        ),
    ]
