# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-19 11:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import libs.stdimage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190326_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='image',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(1200, 1200), upload_to='page', variations={'admin': {'size': (200, 150)}, 'desktop': {'size': (1470, 510)}, 'mobile': {'size': (640, 380)}, 'mobile_2x': {'quality': 80, 'size': (1280, 760)}, 'tablet': {'size': (767, 400)}, 'tablet_2x': {'quality': 80, 'size': (1534, 800)}, 'wide': {'size': (1920, 660)}}, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='text_first',
            field=ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='first text'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='text_second',
            field=ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='second text'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contactsconfig',
            name='header',
            field=models.CharField(max_length=255, verbose_name='header'),
        ),
    ]
