# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210119_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='additional_information',
            field=models.CharField(blank=True, max_length=1024, verbose_name='additional information'),
        ),
        migrations.AddField(
            model_name='message',
            name='basic_goals',
            field=models.CharField(blank=True, max_length=1024, verbose_name='basic goals'),
        ),
        migrations.AddField(
            model_name='message',
            name='bussines_owner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, verbose_name='bussines_owner'),
        ),
        migrations.AddField(
            model_name='message',
            name='date_convenient',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date convenient'),
        ),
        migrations.AddField(
            model_name='message',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='message',
            name='household_income',
            field=models.CharField(choices=[('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='<$100K', max_length=255, verbose_name='household income'),
        ),
        migrations.AddField(
            model_name='message',
            name='investeble_assets',
            field=models.CharField(choices=[('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='<$100K', max_length=255, verbose_name='investeble assets'),
        ),
        migrations.AddField(
            model_name='message',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Not Married', 'Not Married')], default='Married', max_length=255, verbose_name='marital status'),
        ),
        migrations.AddField(
            model_name='message',
            name='number_of_children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=255, verbose_name='number of children'),
        ),
        migrations.AddField(
            model_name='message',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, verbose_name='occupation'),
        ),
        migrations.AddField(
            model_name='message',
            name='real_estate_question',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=(('Yes', 'Yes'), ('No', 'No')), max_length=255, verbose_name='real estate question'),
        ),
        migrations.AddField(
            model_name='message',
            name='spouse_date_birth',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='spouse date birth'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(choices=[('9:00AM', '9:00AM'), ('1:00PM', '1:00PM'), ('3:00PM', '3:00PM')], default='9:00AM', max_length=128, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Full name'),
        ),
    ]
