# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210126_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(editable=False, verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_convenient',
            field=models.DateField(verbose_name='date convenient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='message',
            name='household_income',
            field=models.CharField(choices=[('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='<$100K', max_length=255, verbose_name='household income'),
        ),
        migrations.AlterField(
            model_name='message',
            name='investeble_assets',
            field=models.CharField(choices=[('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='<$100K', max_length=255, verbose_name='investeble assets'),
        ),
        migrations.AlterField(
            model_name='message',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Not Married', 'Not Married')], default='Married', max_length=255, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='number_of_children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=255, verbose_name='number of children'),
        ),
        migrations.AlterField(
            model_name='message',
            name='spouse_date_birth',
            field=models.TimeField(blank=True, verbose_name='spouse date birth'),
        ),
    ]
