# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210127_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='real_estate_question',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, verbose_name='real estate question'),
        ),
    ]
