# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-27 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210127_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date sent'),
        ),
    ]
