# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-27 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210127_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_convenient',
            field=models.DateField(blank=True, verbose_name='date convenient'),
        ),
    ]
