# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20210127_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_convenient',
            field=models.DateField(blank=True, null=True, verbose_name='date convenient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='message',
            name='spouse_date_birth',
            field=models.TimeField(blank=True, null=True, verbose_name='spouse date birth'),
        ),
    ]
