# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-27 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20210127_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='spouse_date_birth',
        ),
    ]
