# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-29 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_message_spouse_date_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYouPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='header')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='change date')),
            ],
            options={
                'verbose_name': 'Thank You page',
                'default_permissions': ('change',),
            },
        ),
    ]
