# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-29 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_thankyoupage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactblock',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
