# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_contactblock_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='address',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='address',
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='coords',
            field=google_maps.fields.GoogleCoordsField(blank=True, help_text='Double click on the map places marker', verbose_name='coords'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='region',
            field=models.CharField(blank=True, max_length=64, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='zip',
            field=models.CharField(blank=True, max_length=32, verbose_name='zip'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
