# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_contactsconfig_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
