# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_defaultform'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultform',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='change date'),
        ),
    ]
