# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-02 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_defaultform_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsconfig',
            name='form_block_description',
            field=models.TextField(blank=True, verbose_name='form block description'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='form_block_header',
            field=models.CharField(blank=True, max_length=256, verbose_name='form block header'),
        ),
    ]
