# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20210202_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Not Married', 'Not Married')], default='Married', max_length=255, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='number_of_children',
            field=models.CharField(choices=[('Blank', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='Blank', max_length=255, verbose_name='number of children'),
        ),
    ]
