# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20210204_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Married', max_length=255, verbose_name='marital status'),
        ),
    ]
