# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-04 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_auto_20210204_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=255, verbose_name='marital status'),
        ),
    ]
