# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_auto_20210204_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='household_income',
            field=models.CharField(choices=[('', ''), ('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='', max_length=255, verbose_name='household income'),
        ),
        migrations.AlterField(
            model_name='message',
            name='investeble_assets',
            field=models.CharField(choices=[('', ''), ('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='', max_length=255, verbose_name='investeble assets'),
        ),
        migrations.AlterField(
            model_name='message',
            name='number_of_children',
            field=models.CharField(choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='', max_length=255, verbose_name='number of children'),
        ),
    ]
