# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20210303_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bussines_owner',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, verbose_name='business owner'),
        ),
    ]
