# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_auto_20210303_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, max_length=1024, verbose_name='how did you hear about us?'),
        ),
    ]
