# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-24 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_auto_20210322_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='investeble_assets',
            field=models.CharField(choices=[('', ''), ('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm'), ('$2mm+', '$2mm+')], default='', max_length=255, verbose_name='investable assets'),
        ),
    ]
