# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-02 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_message_how_did_you_hear_about_us'),
        ('contacts', '0031_auto_20210323_2217'),
    ]

    operations = [
    ]
