# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-20 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_merge_20210402_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_convenient',
            field=models.DateField(blank=True, null=True, verbose_name='Requested date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='household_income',
            field=models.CharField(choices=[('', ''), ('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm')], default='', max_length=255, verbose_name='household income'),
        ),
        migrations.AlterField(
            model_name='message',
            name='investeble_assets',
            field=models.CharField(choices=[('', ''), ('<$100K', '<$100K'), ('$101-250k', '$101-250k'), ('$250-500k', '$250-500k'), ('$500-1mm', '$500-1mm'), ('$1-2mm', '$1-2mm')], default='', max_length=255, verbose_name='investable assets'),
        ),
    ]
