# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0033_auto_20210520_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(choices=[('10:00AM', '10:00AM'), ('1:00PM', '1:00PM'), ('3:30PM', '3:30PM')], default='10:00AM', max_length=128, verbose_name='time'),
        ),
    ]
