# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-20 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_auto_20211111_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_convenient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
