# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-04-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0035_auto_20220120_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='basic_goals1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Education Planning', 'Education Planning'), ('Preparing for retirement', 'Preparing for retirement '), ('Legacy planning', 'Legacy planning'), ('Providing for you and your family in the event of a premature death or disability', 'Providing for you and your family in the event of a premature death or disability'), ('Tax mitigation', 'Tax mitigation'), ('Real Estate', 'Real Estate'), ('Estate Planning', 'Estate Planning'), ('Investment Management', 'Investment Management'), ('Short-term and long-term goals', 'Short-term and long-term goals')], default='', max_length=237),
        ),
        migrations.AddField(
            model_name='message',
            name='isAccepted',
            field=models.BooleanField(default=False, max_length=255, verbose_name='isAccepted*'),
        ),
        migrations.AddField(
            model_name='message',
            name='professional_guidance',
            field=models.CharField(blank=True, max_length=1024, verbose_name='professional_guidance'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_fee_structure',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, verbose_name='read_fee_structure'),
        ),
        migrations.AddField(
            model_name='message',
            name='retirement',
            field=models.CharField(choices=[('', ''), ('0-5 years', '0-5 years'), ('5-10 years', '5-10 years'), ('10-15 years', '10-15 years'), ('15 + years', '15 + years')], default='', max_length=255, verbose_name='retirement'),
        ),
        migrations.AddField(
            model_name='message',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='spouse_name'),
        ),
        migrations.AddField(
            model_name='message',
            name='spouse_retirement',
            field=models.CharField(choices=[('', ''), ('0-5 years', '0-5 years'), ('5-10 years', '5-10 years'), ('10-15 years', '10-15 years'), ('15 + years', '15 + years')], default='', max_length=255, verbose_name='spouse_retirement'),
        ),
        migrations.AddField(
            model_name='message',
            name='stock_options',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, verbose_name='stock_options'),
        ),
    ]
