# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-04-19 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0036_auto_20230419_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='basic_goals1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='isAccepted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='professional_guidance',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_fee_structure',
        ),
        migrations.RemoveField(
            model_name='message',
            name='retirement',
        ),
        migrations.RemoveField(
            model_name='message',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='spouse_retirement',
        ),
        migrations.RemoveField(
            model_name='message',
            name='stock_options',
        ),
    ]
