# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-04-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0038_auto_20230420_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agree',
            field=models.BooleanField(choices=[('', ''), (True, 'I Accept The Minimums Outlined By Colorado Wealth Group In Their Fee Structure.*')], default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='basic_goals1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', ''), ('Education Planning', 'Education Planning'), ('Preparing for retirement', 'Preparing for retirement '), ('Legacy planning', 'Legacy planning'), ('Providing for you and your family in the event of a premature death or disability', 'Providing for you and your family in the event of a premature death or disability'), ('Tax mitigation', 'Tax mitigation'), ('Real Estate', 'Real Estate'), ('Estate Planning', 'Estate Planning'), ('Investment Management', 'Investment Management'), ('Short-term and long-term goals', 'Short-term and long-term goals')], default='', max_length=238),
        ),
    ]
