# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-04-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_auto_20230421_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='spouse_occupation*'),
        ),
    ]
