# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-07-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0040_message_spouse_occupation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': ('delete',), 'ordering': ('-date_now',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='date_now',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='basic_goals1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', ''), ('Education Planning', 'Education Planning'), ('Preparing for retirement', 'Preparing for retirement '), ('Legacy planning', 'Legacy planning'), ('Providing for you and your family in the event of a premature death or disability', 'Providing for you and your family in the event of a premature death or disability'), ('Tax mitigation', 'Tax mitigation'), ('Real Estate', 'Real Estate'), ('Estate Planning', 'Estate Planning'), ('Investment Management', 'Investment Management'), ('Short-term and long-term goals', 'Short-term and long-term goals')], default='', max_length=1024),
        ),
    ]
