# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-07-04 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0041_auto_20230704_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': ('delete',), 'ordering': ('-date',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_now',
            new_name='date',
        ),
    ]
