# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-08-02 06:22
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0044_auto_20230730_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='agree',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('I Accept The Minimums Outlined By Colorado Wealth Group In Their Fee Structure.*', 'I Accept The Minimums Outlined By Colorado Wealth Group In Their Fee Structure.*')], default='', max_length=1024),
        ),
    ]
