# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-05-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0048_auto_20231122_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='how_did_you_hear_about_us',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Web Search', 'Web Search'), ('Email', 'Email'), ('Client Referral', 'Client Referral'), ('Professional Referral', 'Professional Referral'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], default='', max_length=1024),
        ),
    ]
